### ISSUE TITLE
Setup Unverified role through the bot?

### ISSUE THREAD

**Issue by BoomerangMario** [ErisTheEagleArt/advancewelcomebot.py#1]
Maybe you should make a command within the bot where the bot can set up the Unverified role for your server for what the bot gives you when you join the server and maybe to set up the verify channel.
That would be cool.

**Comment by MatthewsDevelopment** [comment]
I agree

**Comment by EagleTribeEris** [comment]
This has been modified to have this. Check out the updated code.
