### ISSUE TITLE
Only works with discord.py 1.7.x

### ISSUE THREAD

**Issue by BadUserHater** [ErisTheEagleArt/advancewelcomebot.py#2]
This source code only works in discord.py 1.7.x

With the way on how the slash commands work and the way it welcomes members, it only works in discord.py 1.7.x so you should edit the requirements file to be discord.py==1.7.1
I like Discord.py 1.7.1. I think they have 1.7.3 as well.

I don't know if there is a way to fix this for discord.py 2.0

**Comment by EagleTribeEris** [comment]
Since Discord.py 1.7.x does not work anymore, I will update the code to work with Discord.py 2.0 with removal of Slash command support.

**Comment by EagleTribeEris** [comment]
This issue has been solved. Made the code work in discord.py 2.0.
